notifications:
  webhooks:
    urls:
      - https://hooks.glipdemo.com/webhook/8a0601f2-b7f1-440b-83b0-dd484e459701
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never 
