notifications:
  webhooks:
    urls:
      - https://hooks.glipdemo.com/webhook/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvdCI6InUiLCJvaSI6IjE1NTI4ODg2Mjc1IiwiaWQiOiIyNDY3MTAyOTkifQ.3fR4Dwk-_xqXCbeeOrshrbV0Ca-RIqzcpPfJb7SRRnQ
